# -*- mode: ruby -*-
# vi: set ft=ruby :

#Ruta del directorio actula
dir = File.dirname(File.expand_path(__FILE__))
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ServidorLocal"

  # Host-only network configuration
  # config.vm.network :public_network,:bridge=>"eth0" # Se conecta a la misma red que el anfitrion
  # config.vm.network :public_network

  config.vm.network "private_network", ip: "192.168.5.20"
  config.vm.synced_folder "../../Codigo/servidor" , "/var/www", :mount_options => ["dmode=777", "fmode=777"]
  config.vm.synced_folder "./COMPARTIDA" , "/home/vagrant", :mount_options => ["dmode=777", "fmode=777"]

  config.vm.provider :virtualbox do |vb|
    #Abre una ventana con la maquina
    vb.gui = false

    # configuracion de la maquina virtual
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--name"  , "ServidorLocal"]
    vb.customize ["modifyvm", :id, "--cpus"  , 1]
    #vb.customize ["modifyvm", :id, "--chipset", "ich9"]
  end

  # Instaladores
  config.vm.provision "shell", path: "scripts/vagrant-bootstrap.sh"
end

# Pequeño manual http://www.conasa.es/blog/vagrant-configuracion-basica-de-la-maquina-virtual/
# Otro tutorial mas https://www.adictosaltrabajo.com/tutoriales/vagrant-install/#5.%20Como%20instalo%20software%20de%20forma%20que%20lo%20vean%20mis%20compa%C3%B1eros?
